# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('monto', models.FloatField(default='200.00')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('montototal', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meses', models.ManyToManyField(through='appcondominio.Factura', to='appcondominio.Mes')),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcondominio.Mes'),
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcondominio.Pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcondominio.Residente'),
        ),
    ]
